#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.
include $(srctree)/drivers/misc/mediatek/Makefile.custom

#obj-$(CONFIG_FINGERPRINT_JMT103) := jmt_merge.o
obj-y := jmt_merge.o

