#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.
include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y  += et310-spi.o
obj-y  += mt_fps_trigger.o
